/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface faculties {
  "id"?: string 
  "first_name": string 
  "middle_name": string | null 
  "last_name": string 
  "address": string | null 
  "phone_number": string | null 
  "username": string 
  "password": string 
  "privilege": number 
  "is_deactivated"?: boolean 
  "created_at"?: any 
  "updated_at"?: any 
}
export interface sessions {
  "session_token": string 
  "ip_address": any 
  "user_agent": string | null 
  "type": string 
  "id": string 
  "is_revoked"?: boolean 
  "expiration_date": any 
  "created_at"?: any 
}
export interface students_credentials {
  "student_id": string 
  "username": string 
  "password": string 
  "updated_at"?: any 
}

export interface system_components_clients{
  "api_key": string 
  "client_name": string 
  "component": number 
  "is_revoked"?: boolean 
}