/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface academic_term {
  "id"?: string 
  "name": string 
  "is_hidden": boolean 
  "created_at"?: any 
  "updated_at"?: any 
}
export interface api_key {
  "key"?: string 
  "name": string 
  "privilege": number 
  "is_revoked"?: boolean 
}
export interface attendance_tracker_device {
  "id"?: string 
  "name": string 
  "key": string 
  "is_revoked"?: boolean 
  "created_at"?: any 
  "updated_at"?: any 
}
export interface attendance {
  "id"?: string 
  "device_id": string 
  "enrollment_id": string 
  "check_type": number 
  "created_at"?: any 
}
export interface course_schedule {
  "id"?: string 
  "course_id": string 
  "subject_id": string 
  "time_start": any 
  "time_duration": any 
  "created_at"?: any 
  "updated_at"?: any 
}
export interface course {
  "id"?: string 
  "name": string 
  "is_hidden"?: boolean 
  "created_at"?: any 
  "updated_at"?: any 
}
export interface enrollment {
  "id"?: string 
  "academic_term_id": string 
  "student_id": string 
  "course_id": string 
  "is_hidden": boolean 
  "is_revoked": boolean 
  "created_at"?: any 
}
export interface grade {
  "id"?: string 
  "enrollment_id": string 
  "subject_id": string 
  "grade": any 
  "is_hidden": boolean 
  "updated_at"?: any 
}
export interface management_account {
  "id"?: string 
  "username": string 
  "password": string 
  "privilege": number 
  "is_deactivated"?: boolean 
  "created_at"?: any 
  "updated_at"?: any 
}
export interface student {
  "id"?: string 
  "school_id": string | null 
  "first_name": string 
  "middle_name": string 
  "last_name": string 
  "address": string 
  "sex": string 
  "birth_date": Date 
  "phone_number": string | null 
  "email_address": string | null 
  "username": string | null 
  "password": string | null 
  "is_currently_enrolled": boolean 
  "created_at"?: any 
  "updated_at"?: any 
}
export interface subject {
  "id"?: string 
  "teacher": string 
  "is_hidden": boolean 
  "created_at"?: any 
  "updated_at"?: any 
}

